spring:
  redis:
    port: 6379
    host: 127.0.0.1
    password:
  datasource:
    url: jdbc:mysql://106.15.205.21:3306/shiro_redis?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: lyf
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource



